### ISSUE TITLE
Permission denied when mkdir -p "/data/$CLUSTER_NAME/" 

### ISSUE THREAD

**Issue by liolok** [Wollwolke/dst-dedicated-server#1]
```log
main  | mkdir: cannot create directory '/data/dst.moe/': Permission denied                                                                                                                   
main  | No cluster_token set or found
```

**Comment by Wollwolke** [comment]
The first error is a permission error, the mounted directory needs to be owned by the uid 1000. I added a section in the doc and a more verbose error message.

Regarding the second issue: Did you provide a cluster token in the compose file?

**Comment by liolok** [comment]
The directory should've be mounted well and its owner is 1000:1000 for sure. And the token was in the cluster_token.txt file, I didn't write it to compose file.

I went to systemd-nspawn and built an environment from scratch, based on Ubuntu 20.04. Wish your project the best, anyway.
